---
- name: Install NVMe CLI tools
  ansible.builtin.package:
    name: nvme-cli
    state: present

- name: Install EBS mapper script
  ansible.builtin.copy:
    src: ebs-nvme-mapping.sh
    dest: /usr/local/sbin/ebs-nvme-mapping
    owner: root
    group: root
    mode: 0755

- name: Install udev rules
  ansible.builtin.copy:
    src: 999-aws-ebs-nvme.rules
    dest: /etc/udev/rules.d/
    owner: root
    group: root
    mode: 0644

- name: Trigger udev rules now
  ansible.builtin.command: udevadm trigger
...
