---
# tasks file for ebs-automatic-nvme-mapping
- name: Check whether any NVMe devices exist on the system
  ansible.builtin.find:
    paths: /dev
    recurse: no
    file_type: any
    patterns: 'nvme[0-9]*'
  register: nvme_devices
  
- name: Import mapping tasks for NVMe systems
  import_tasks: configure_mapping.yml
  when: (nvme_devices.matched > 0) or force_run
...
