apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCemDGbcC6czBxi0GC9rIpOJfyqpO0CQu3o1eLv6E0ZWW+2axyMBfx59MWlrrtWYNwAqbd3JSLN9g9lf/ihwXxmdydcTmqu/n0K7A5jIz3z6b5Qmq4upzL6abhe8YJhF404rSek5//DgX4yl7RJh1419wyIzJPMWwg2FtJC+LJaAC/FQzjPJplgr6zPeuJbPSwE1PvgQbuKElF6+jK9UB/5bZdt/9ASF1oZyYygxh3jy7Jduz7FaoeJkyurzIoGXlsDp9FkTk2qsYHj5F3va1Tgig1E+jMQ6v5YtWDfTmifLqdP5v7tGTfy2GV3+egoHOBl8dWZrfMTGPWvZDvgKJtHOdC0jJzp+Bh4BLi+etqun71E61K7oJ4mIoKPGgWEThqBW0k0+ETGyebekOTRPCfEyaoNC5FtIZF8Z85iIJvaYN5xumzehPH/xbYNCBiZTHrXEOBia1gAv9Vi/W2uzMU1D02IS7g+Gn7ZKiaqSe9VhhbrylVBAKW2kxO+llKuiJHon/HnuVJp2BTqcb4H4LotfJJxuNdIPaiCZlmK2DS9ZhdB0elF6fzAQmVC3dLgs4F4Ani47/gqMahCmUfME4H4LVAiW9WYCJHr3Lxlr3cdrRwT9rZCRN4JBmfj9uFqdWtA8gqnEwYWS3DuNqvjknGV6Hj3ckhZ/tdSRninxd3M8JyIFAG4OmY9A7mzwcBG4odWYgYdHG2B7IS0/30gF8scgHAZFbvdUPk/fc4QsFc7duO4l3PdUZJS
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager

