apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgBdivTlMnQOLG95c93oOiHcOJm0etVMAGTD/zbEHwCf8PdCnsLcSQNch7lYI55mFdz0v+wT9rH2MWlBToweeIJs5JIKDjEn4NmFbXPicW3E91Q63jvpT0dJbeFm2ESlNVy76ZSh/4ESbiBb9fx92VraeP75DziDVsVhc6szt3MterzIePlHO2856DF9hY9wMlKK5DTLYfmTQ6OYbxq6ziLm1j3WaBt0KjkxNnPlpb4eNAWS547R0uSVLoMhkrSOAe2FQY04yFxm66SdXshOUsnpGuMqbv0GkXi6GaeBBCeZ4D/dUdwfRy6Fuu07bTR+ee9f0Z7ZQ1Pf6V/Wy0vFBiz2DiQ7+QRFy3jGGRftmxoaeqwmqNQMANNo6G/liY0IO2gMHHWzWT6MBUQtLzW2rggaf5CaD4TvUq4EZ6DKzy7awoerqviUcPKyErobydYevE4O3rie7v4gFavlYL4Zihsc4CS5+GygpDLNr01L57Hm5/LPGcE96UAKYDt8wh0q76sc73MC8VAyQS3Sfpe25jDXkRfU+/+tJbqP9SKDAfCvqRhlfKkYs6+VoFF3DzecPlPoXIJ8d49Ihf/OJUKOgylmRdreHCDcFloqLPp2G2UawUzPm9DI4Kfn/5rzCft7OuXBIt8RJaxGs2f3gY3GFvJG+7iOwvSnKBsU+Q8XqTqxU8ydM84ILjhyHjO6o4pMuiljWTXFzZnp3vYkNECnQucIWwYINN05+auJJG7n1zxUw0mia9WR7SNC
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns

