apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgAOm+UI0/7seiDTp5Ps/2FNJs1gv1OLBkwLIoRwcTo1lt37M18XmTZRN40jr+OmJm08pmBVQWzM1sWc8NohqvqyFY+RSjXCapMbqkFmJq7UDaofIMwRkh4/gBNqftdKuYixfjrJHcD9efngy/7IyjvPCYPqLtT6grSB7hKDTpFuqX+X7pW5N+F0vh0j3hs4RQ0S/iiAuxUrX8stWvr8bv2AxgZ1RFIyP5/cjpSBb5Sg60bnBGILKz2GeLWa7kTKgpA5fZLBvFSzPg4QFXIrXTLib4UW1rbmYwAKmFQz1ENsAHBHlJg4k+HJyYx3g1wopmRtmuFuBs5W2RHrU5lRV1V17VivGrMWX+ECrZuKY3lpKi/eqF7/9QIHfw0Dm42CVy3UR2KIFBtSOCwLBx+8tmWDfaD/ZWHdqKTN5upUu2MQmVPVhb7+8ZdS00MK852NmmcCsjiQMSLs9hqoKjruvkn353f7R23lIOGAcH4+nqod1v42br9VpVJK8Tz7DJStPNkzLHoEOPEx6VfmLyDl1I1GBihUqHO2vilEL+BYWgulxA/a/mWnl+TfH5irah6kOdtLPuL7cptjXM2WGoyRa9yQMKD8sMivFPYS06cTzUVa0XmAIvIR5SOkhZv11lBjI6SkhthrsfVMBi7/c8+ADdPPHzmXHOMDYnOsSNv75oZ2l9h1YvWyyM7vqo1lnmPbQJL4fjECjoB7FmFSqrK8KEIqenWwe8b7bqcyTeTJgb7Q9pG1F7D9bz8D
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns

