apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 1h0m0s
  releaseName: external-dns
  targetNamespace: external-dns
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: ">=6.0.0"
  values:
    resources:
      limits:
        memory: 50Mi
      requests:
        memory: 50Mi
        cpu: 10m
    policy: sync
    registry: "txt"
    txtOwnerId: "k8s-ebi-gallery-external-dns"
    rbac:
      create: true
    provider: cloudflare
    domainFilters: [ "iangrant.me" ]
    digitalocean:
      secretName: cloudflare-api-token
