apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebi-gallery-frontend
  namespace: default
  labels:
    tier: frontend
    layer: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
      layer: webserver
  template:
    metadata:
      labels:
        tier: frontend
        layer: webserver
    spec:
      containers:
        - name: frontend-nginx
          image: igrnt/ebi-gallery-frontend:1.1.1
          ports:
            - containerPort: 80
          env:
            - name: FPM_HOST
              value: ebi-gallery-backend:9000
---
apiVersion: v1
kind: Service
metadata:
  name: ebi-gallery-frontend
  namespace: default
spec:
  selector:
    tier: frontend
    layer: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ebi-gallery-frontend
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging-cloudflare"
spec:
  tls:
  - hosts:
    - ebi-gallery-do.iangrant.me
    secretName: ebi-gallery-tls
  ingressClassName: nginx
  rules:
  - host: ebi-gallery-do.iangrant.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ebi-gallery-frontend
            port:
              number: 80
