variable "aws_region" {
  description = "AWS region to use for resource creation"
  type        = string
  default     = "us-east-1"
}

variable "ec2_instance_size" {
  description = "Compute size/type to use for EC2 instance creation, in AWS slug format"
  type        = string
  default     = "t2.micro"
  # N.b. t2.micro is a bit weedy for building the Docker images locally,
  # which this deployment does by default. Recommended is t3.small or better,
  # or changing the docker-compose file to pull the pre-built images from 
  # Docker Hub instead of building.
}

variable "generated_key_name" {
  description = "Filename to write the SSH key pair generated by Terraform to"
  type        = string
  default     = "ebi_gallery_key"
}

variable "app_name" {
  description = "Configurable base name to use for the tags, etc in AWS"
  type        = string
  default     = "ebi-gallery"
}
